[package]
name = "third_angle_of_a_triangle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "third_angle_of_a_triangle"
path = "main.rs"
