[package]
name = "find_the_smallest_integer_in_the_array"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "find_the_smallest_integer_in_the_array"
path = "main.rs"
